name: Publish Docs

on:
  workflow_call:
    inputs:
      plan:
        required: true
        type: string

permissions:
  contents: write

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    env:
      PLAN: ${{ inputs.plan }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install docver
        uses: sigoden/install-binary@v1
        with:
          repo: ${{ github.repository }}
          tag: ${{ github.ref_name }}
          name: docver

      - name: Resolve docver path
        run: |
          set -euo pipefail
          DOCBIN="$(command -v docver)"
          test -n "$DOCBIN"
          echo "DOCVER_BIN=$DOCBIN" >> "$GITHUB_ENV"

      - name: Build docs (optional)
        run: |
          echo "Build any site generator here if needed"

      - name: Deploy using docver
        uses: ConnerPetzold/docver-publish@v0.1.0
        with:
          docver-path: ${{ env.DOCVER_BIN }}
          path: out
          version: ${{ github.ref_name }}
          aliases: latest
          push: true
