name: Publish Docs

on:
  workflow_call:
    inputs:
      plan:
        required: true
        type: string

permissions:
  contents: write

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    env:
      PLAN: ${{ inputs.plan }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install versite
        uses: sigoden/install-binary@v1
        with:
          repo: ${{ github.repository }}
          tag: ${{ github.ref_name }}
          name: versite

      - name: Resolve versite path
        run: |
          set -euo pipefail
          DOCBIN="$(command -v versite)"
          test -n "$DOCBIN"
          echo "VERSITE_BIN=$DOCBIN" >> "$GITHUB_ENV"

      - name: Build docs (optional)
        run: |
          echo "Build any site generator here if needed"

      - name: Deploy using versite
        uses: ConnerPetzold/versite-publish@v0.1.0
        with:
          versite-path: ${{ env.VERSITE_BIN }}
          path: out
          version: ${{ github.ref_name }}
          aliases: latest
          push: true
